services:
  - type: web
    name: gmo-bot  # ← 名前もわかりやすく変更すると吉
    env: python
    plan: starter
    buildCommand: ""
    startCommand: python webhook_bot.py
    envVars:
      - key: BITGET_API_KEY
        sync: false
      - key: BITGET_API_SECRET
        sync: false
      - key: BITGET_API_PASSPHRASE
        sync: false
    autoDeploy: true
