services:
  - type: web
    name: gmo-bot
    env: python
    plan: starter  # ← ここを starter に！
    buildCommand: ""
    startCommand: python webhook_bot.py
    envVars:
      - key: GMO_API_KEY
        sync: false
      - key: GMO_API_SECRET
        sync: false
    autoDeploy: true
